DISPLAY_DEPTH = 3
LABEL_CROP_LENGTH = 50
LABEL_MAX_LENGTH = 300
ACTUALS_MAX_LENGTH = LABEL_MAX_LENGTH // 10
MAX_ELEMENTS = 500
MAX_SAMPLE_TIME_MS = 12_000

INPUT_N = 3
CMP_ALGORITHM_I = 0
SHOW_FULL_LABELS = False

USER_STATE_STORAGE_TYPE = "session"
