DISPLAY_DEPTH = 3
LABEL_CROP_LENGTH = 50
LABEL_MAX_LENGTH = 300
ACTUALS_MAX_LENGTH = LABEL_MAX_LENGTH // 10
MAX_ELEMENTS = 500
MAX_SAMPLE_TIME_MS = 12_000
MAX_CACHED_HEAP_COUNT = 50
MAX_CACHED_DECISION_TREES = 10
SAMPLE_SEED = 514
PROGRESS_INTERVAL_MS = 300

INPUT_N = 3
INPUT_N_MAX = 500
CMP_ALGORITHM_I = 0
SHOW_FULL_LABELS = False

USER_STATE_STORAGE_TYPE = "session"
